### ISSUE TITLE
Use template for types of VMs

### ISSUE THREAD

**Issue by sah4ez** [dhlab-tech/vm#4]
If we will have a many VMs in cluster, need describe them in vars file through template.
As example:
```
etcd:
  count: 3
  image_name: "seme_image%d.img"
  max: "00:00:00:00:%d"
  hostname: "etcd%d"
```
